# Generated by Django 5.0.7 on 2024-07-17 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service_rest", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="automobilevo",
            name="technician",
        ),
    ]
