# Generated by Django 5.0.7 on 2024-07-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_rest", "0002_remove_automobilevo_technician"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automobilevo",
            name="vin",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
