# Generated by Django 4.0.3 on 2025-01-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_rest', '0003_remove_vehiclemodel_picture_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobile',
            name='price',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=10),
        ),
    ]
