# Generated by Django 5.0.7 on 2025-01-22 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_rest", "0004_automobile_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automobile",
            name="price",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(9999999999)],
            ),
        ),
    ]
